### ISSUE TITLE
啊，正好都差一个。

### ISSUE THREAD

**Issue by zds-jack** [game-helper/eleme#1]
9个领最多，我是第8个。
5个领最多，我是第4个。。。。。。

**Comment by zhuweiyou** [comment]
有截图或者红包链接吗？我这边试了很多个都是正常的呢。

多人同时访问，我没有进行处理，可能别人也在刷，串号了。。

最稳定的办法是自己弄小号，修改 [src/cookie.js](https://github.com/game-helper/eleme/blob/master/%E6%8B%BC%E6%89%8B%E6%B0%94%E7%BA%A2%E5%8C%85/src/cookie.js)

**Comment by zds-jack** [comment]
好的，是姿势不对。我点开了。请问这个又每天5个的上限吗

**Comment by zhuweiyou** [comment]
小号因为是每次随机的所以没上限。

大号官方说 5 个，我没具体试验。

5 个不够你用吗？这个有效期很短的。

**Comment by helloxcq** [comment]
请问饿了么的红包链接该怎么获得啊？

**Comment by zds-jack** [comment]
有2个方法：① 在微信网页版里面，右键可以看见打开链接。② 在微信移动端，可以把登录的饿了么账户退出，就可以直接复制链接了

**Comment by zhuweiyou** [comment]
@helloxcq 

分享到 QQ，然后用电脑复制下链接即可。

不分享到微信的原因是，如果你之前授权过，进去就被领掉了。。

**Comment by helloxcq** [comment]
@zhuweiyou @zds-jack 嗯嗯 可以了 感谢！
还有个问题就是使用的时候出现了如下问题:
connect ENETUNREACH 203.189.242.35:443
这个是因为啥啊

**Comment by zhuweiyou** [comment]
多给点上下文的信息，看起来是网络原因。
