### ISSUE TITLE
想学习下node.js，可惜按照之前的说明部署不起来。。

### ISSUE THREAD

**Issue by MAYBreath** [game-helper/eleme#13]
按教程nmp i 之类的 一直出错。。现在部署说明直接移除了。。
不知道能否给个详细的部署说明，打算从本项目学习下。

**Comment by zhuweiyou** [comment]
说明加回去了，你的报错截图 log 发一下

**Comment by MAYBreath** [comment]
之前的编译部署没通过，最新的一次通过了。。感谢。
顺便问下这个nodejs为何需要一次跑4个进程app，不是应该就一个麽

**Comment by zhuweiyou** [comment]
开几个进程按照 CPU 核心数来，做负载均衡，网络请求属于 IO 密集，多开好。就算单核，最好 2 个以上，这样在重启的那几秒钟，另一个还能正常提供服务，否则此时有用户进来网站就挂了。

另外 nodejs 貌似单进程有最大内存限制 (当然这个项目不吃内存，才几十 mb 一个进程)

**Comment by zhuweiyou** [comment]
你可以看一下 pm2 reload 是挨个重启的
