### ISSUE TITLE
最大红包是第八个，比如已经领到了第七个了，用这个抢，最大的红包就会被虚拟的账户抢掉

### ISSUE THREAD

**Issue by ishwy** [game-helper/eleme#17]
![Uploading image.png…]()

**Comment by zhuweiyou** [comment]
因为小号有限，并发请求时，准备换你的手机号去领最大时，刚好被其它人请求绑到随机小号了

所以确实有几率会出现这种情况，你只能再找个红包链接咯

> 建议避开高峰使用（每天高峰期 10 ~ 12 点左右）

**Comment by ishwy** [comment]
明天在测试一下

**Comment by zhuweiyou** [comment]
哦，我看错问题了，你这个确实是这样。用这个领的时候，优先会用小号去试一下，看看还有几个到最大

**Comment by ishwy** [comment]
哈哈，麻烦了

**Comment by zhuweiyou** [comment]
再搞个链接领就行了
