### ISSUE TITLE
新的问题无法请求的链接出现了

### ISSUE THREAD

**Issue by MAYBreath** [game-helper/eleme#19]
![111](https://user-images.githubusercontent.com/9080733/36644703-49dfadea-1a99-11e8-8549-82b8a268a7af.jpg)

正常流程分享出来的红包 饿了么有时候会是这种缩短域名后的格式
http://url.cn/5vppds7
这个链接无法请求，如果自己打开看真实地址的话 可能导致直接被误领。。
大佬能否做下识别这种链接？

**Comment by MAYBreath** [comment]
这个地址是腾讯的缩短的域名，可能本身这个链接是没有缩短的，只是我用发送到QQ的PC电脑或者其他群就缩短了。。出现的概率也不一定，有时候会有有时候没有

**Comment by zhuweiyou** [comment]
已支持

**Comment by MAYBreath** [comment]
大佬威武！神速！
