### ISSUE TITLE
红包被非填入手机号领走了

### ISSUE THREAD

**Issue by lanjeason** [game-helper/eleme#2]

**Comment by zhuweiyou** [comment]
红包链接发一下

**Comment by qcyclone** [comment]
https://h5.ele.me/hongbao/#hardware_id=&track_id=&platform=4&sn=10e37ec1ef8f3c66&theme_id=2153&device_id=
都是小号吧，我填入的是156

**Comment by zhuweiyou** [comment]
@qcyclone 参数上缺失了 `lucky_number` 程序无法判断何时该用大号去领取红包。

是饿了么更新了？

原先正常的地址应该是：

```
https://h5.ele.me/hongbao/#
hardware_id=
is_lucky_group=
lucky_number=第几个是大红包
track_id=
platform=
sn=
theme_id=
device_id=
```
