### ISSUE TITLE
请问这个小号是手机号吧,怎么弄来的

### ISSUE THREAD

**Issue by dj940212** [game-helper/eleme#3]

**Comment by zhuweiyou** [comment]
你可以看下代码

[src/cookie.js](https://github.com/game-helper/eleme/blob/master/%E6%8B%BC%E6%89%8B%E6%B0%94%E7%BA%A2%E5%8C%85/src/cookie.js) - 准备了 10 个 QQ 小号，复制登录态存在这

然后这边随机的手机号，饿了么没有做手机号验证

https://github.com/game-helper/eleme/blob/a15dc0e02fd5b122aa7b8b76266fd7de525ba13d/%E6%8B%BC%E6%89%8B%E6%B0%94%E7%BA%A2%E5%8C%85/src/request.js#L27-L35

**Comment by dj940212** [comment]
@zhuweiyou 原来如此, 美团是不是不能用这种方法实现

**Comment by zhuweiyou** [comment]
美团要验证码，所以不能这样实现。

初步构想可以做一个共享小号的平台。

要使用服务的，必须先共享至少一个已绑手机的小号。

**Comment by dj940212** [comment]
@zhuweiyou 这样是不是不能保证每人每天可以领取一个大包

**Comment by zhuweiyou** [comment]
只要小号多，用小号去顶小包。。不过有点麻烦

**Comment by dj940212** [comment]
@zhuweiyou 感谢分享,准备去弄小号了😄

**Comment by zhuweiyou** [comment]
自己弄小号，只能是你自己用，单号应该有领取限制。

**Comment by dj940212** [comment]
@zhuweiyou 嗯嗯, 我去试试

**Comment by zhuweiyou** [comment]
如果能成功的话，欢迎加入我们 org，一块开发。

**Comment by dj940212** [comment]
@zhuweiyou 👌

**Comment by cloudZQY** [comment]
也就是说这十个小号，领到随机的假的手机号上去了，然后单号限制只限制手机号不限制qq是吗？

**Comment by zhuweiyou** [comment]
@cloudZQY  可以这么说

**Comment by LeachZhou** [comment]
一起一起啊，带我一个

**Comment by zhuweiyou** [comment]
已支持美团

@LeachZhou 
@dj940212 
@cloudZQY

**Comment by CPK1021** [comment]
能说下实现美团的原理吗，大佬

**Comment by zhuweiyou** [comment]
@CPK1021  代码不是开源了吗，直接看咯。随机小号

**Comment by tuzhis** [comment]
> 美团要验证码，所以不能这样实现。
初步构想可以做一个共享小号的平台。
要使用服务的，必须先共享至少一个已绑手机的小号。

@zhuweiyou 有半年不需要点外卖了，看到你这个项目很有感触，自己的经历去年7月底发现美团有泄露红包领取人全部信息的漏洞也弄了个领红包，后来依次经历了开启token验证-》改版token验证-》采用ewxinfo，由于是真实openid也就小范围使用，开放的想法也和上面的差不多一直没空去实现，没想到现在还能这样，点赞点赞

**Comment by zhuweiyou** [comment]
@tuzhis 

我开始以为搞不了了，后来尝试了一下伪造 openid 结果成功了。
