### ISSUE TITLE
如果手机号达到了领取上限，会直接返回Request 400错误，可以优化一下。

### ISSUE THREAD

**Issue by yizhichengxuyuan** [game-helper/eleme#6]
![_15179746499470](https://user-images.githubusercontent.com/22163837/35897282-643f8874-0bfb-11e8-87ac-ac55f4752c4e.png)

**Comment by zhuweiyou** [comment]
看日志确实有不少 400 的情况，但是不确定**是否全部都这个问题**

**Comment by zhuweiyou** [comment]
目前发现有的 400 饿了么会返回请求繁忙

所以目前加了 400 自动重试一次

**Comment by yizhichengxuyuan** [comment]
@zhuweiyou ok，辛苦

**Comment by zhuweiyou** [comment]
已优化
